#!/usr/bin/env sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config window_gap           2
bspc config border_width         2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a obs desktop='^10'

# Reload xrdb
xrdb ~/.Xresources

# Start discord and steam
steam &
discord --ozone-platform=x11 &
obs --startreplaybuffer --minimize-to-tray &

# Start easyeffects service
dex ~/.config/autostart/easyeffects-service.desktop &

