#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

if xrandr -q | grep "HDMI-0 connected"; then
    bspc monitor HDMI-0 -d I II III VII VIII
    bspc monitor DP-0   -d IV V VI IX X
else
    bspc monitor DP-0   -d I II III IV V VI VII VIII IX X
fi

bspc config border_width 1
bspc config window_gap   0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_follows_monitor true
bspc config focus_follows_pointer   true
bspc config pointer_motion_interval 7ms

bspc rule -a Code desktop=IV follow=on
bspc rule -a Steam desktop=VI follow=on
bspc rule -a "Microsoft Teams - Preview" desktop=IX follow=off
bspc rule -a discord desktop=I follow=off
bspc rule -a obs desktop=III follow=off
bspc rule -a android-messages-desktop desktop=VIII follow=off

# Autostart
[ -z ${BSPWM_OPENED+x} ] && dex -a && BSPWM_OPENED=1

# Set background
feh --bg-scale ~/.config/wall > $HOME/.log/feh.stdout 2> $HOME/.log/feh.stderr
# Polybar
$HOME/.config/polybar/launch_polybar.sh > $HOME/.log/polybar.stdout 2> $HOME/.log/polybar.stderr

# pkill light-locker ; light-locker

picom & > $HOME/.log/picom.stdout 2> $HOME/.log/picom.stderr

notify-send "Refreshed BSPWM"
