# Set gsettings
exec_always {
  gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3-dark'
  gsettings set org.gnome.desktop.interface icon-theme 'Adwaita'
  gsettings set org.gnome.desktop.interface cursor-theme 'macOSMonterey'
  gsettings set org.gnome.desktop.interface font-name 'Cantarell 11'
  gsettings set org.gnome.desktop.wm.preferences button-layout ':close'
}

# Cursor theme needs to be set for the seat too

seat seat0 xcursor_theme macOSMonterey